/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 548fd77d28ab85769c4ef1fb9d50321eb5044ea8 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_ShowSimpleMessageBox, 0, 4, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, flags, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, message, IS_STRING, 0)
	ZEND_ARG_OBJ_INFO(0, window, SDL_Window, 1)
ZEND_END_ARG_INFO()

ZEND_FUNCTION(SDL_ShowSimpleMessageBox);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(SDL_ShowSimpleMessageBox, arginfo_SDL_ShowSimpleMessageBox)
	ZEND_FE_END
};

static void register_SDL_messagebox_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("SDL_MESSAGEBOX_ERROR", SDL_MESSAGEBOX_ERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_MESSAGEBOX_WARNING", SDL_MESSAGEBOX_WARNING, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_MESSAGEBOX_INFORMATION", SDL_MESSAGEBOX_INFORMATION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT", SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT", SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT, CONST_PERSISTENT);
}
