/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 75ff32aee44f8b0a3944d44aced960a7a6889232 */

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_SDL_GetKeyboardFocus, 0, 0, SDL_Window, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_StartTextInput, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, window, SDL_Window, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_StopTextInput arginfo_SDL_StartTextInput

#define arginfo_SDL_TextInputActive arginfo_SDL_StartTextInput

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetGamepads, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_IsGamepad, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, instance_id, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_SDL_OpenGamepad, 0, 1, SDL_Gamepad, 1)
	ZEND_ARG_TYPE_INFO(0, instance_id, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_CloseGamepad, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, gamepad, SDL_Gamepad, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetGamepadName, 0, 1, IS_STRING, 1)
	ZEND_ARG_OBJ_INFO(0, gamepad, SDL_Gamepad, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetGamepadID, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, gamepad, SDL_Gamepad, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_GetGamepadSerial arginfo_SDL_GetGamepadName

#define arginfo_SDL_GetGamepadPath arginfo_SDL_GetGamepadName

#define arginfo_SDL_GetGamepadPlayerIndex arginfo_SDL_GetGamepadID

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_SetGamepadPlayerIndex, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, gamepad, SDL_Gamepad, 0)
	ZEND_ARG_TYPE_INFO(0, player_index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetGamepadButton, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, gamepad, SDL_Gamepad, 0)
	ZEND_ARG_TYPE_INFO(0, button, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetGamepadAxis, 0, 2, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, gamepad, SDL_Gamepad, 0)
	ZEND_ARG_TYPE_INFO(0, axis, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_UpdateGamepads, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_GetJoysticks arginfo_SDL_GetGamepads

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_SDL_OpenJoystick, 0, 1, SDL_Joystick, 1)
	ZEND_ARG_TYPE_INFO(0, instance_id, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_CloseJoystick, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetJoystickName, 0, 1, IS_STRING, 1)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_GetJoystickSerial arginfo_SDL_GetJoystickName

#define arginfo_SDL_GetJoystickPath arginfo_SDL_GetJoystickName

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetJoystickPlayerIndex, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_SetJoystickPlayerIndex, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, player_index, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_GetNumJoystickAxes arginfo_SDL_GetJoystickPlayerIndex

#define arginfo_SDL_GetNumJoystickButtons arginfo_SDL_GetJoystickPlayerIndex

#define arginfo_SDL_GetNumJoystickHats arginfo_SDL_GetJoystickPlayerIndex

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetJoystickAxis, 0, 2, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, axis, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetJoystickButton, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, button, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_GetJoystickHat, 0, 2, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, hat, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_UpdateJoysticks arginfo_SDL_UpdateGamepads

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_AttachVirtualJoystick, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, desc, SDL_VirtualJoystickDesc, 0)
ZEND_END_ARG_INFO()

#define arginfo_SDL_DetachVirtualJoystick arginfo_SDL_IsGamepad

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_SetJoystickVirtualAxis, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, axis, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_SetJoystickVirtualButton, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, button, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, down, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SDL_SetJoystickVirtualHat, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, joystick, SDL_Joystick, 0)
	ZEND_ARG_TYPE_INFO(0, hat, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_SDL_Gamepad___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_SDL_Gamepad_pointer, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_SDL_Gamepad_fromPointer, 0, 1, IS_STATIC, 0)
	ZEND_ARG_TYPE_INFO(0, pointer, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_SDL_Joystick___construct arginfo_class_SDL_Gamepad___construct

#define arginfo_class_SDL_Joystick_pointer arginfo_class_SDL_Gamepad_pointer

#define arginfo_class_SDL_Joystick_fromPointer arginfo_class_SDL_Gamepad_fromPointer

ZEND_FUNCTION(SDL_GetKeyboardFocus);
ZEND_FUNCTION(SDL_StartTextInput);
ZEND_FUNCTION(SDL_StopTextInput);
ZEND_FUNCTION(SDL_TextInputActive);
ZEND_FUNCTION(SDL_GetGamepads);
ZEND_FUNCTION(SDL_IsGamepad);
ZEND_FUNCTION(SDL_OpenGamepad);
ZEND_FUNCTION(SDL_CloseGamepad);
ZEND_FUNCTION(SDL_GetGamepadName);
ZEND_FUNCTION(SDL_GetGamepadID);
ZEND_FUNCTION(SDL_GetGamepadSerial);
ZEND_FUNCTION(SDL_GetGamepadPath);
ZEND_FUNCTION(SDL_GetGamepadPlayerIndex);
ZEND_FUNCTION(SDL_SetGamepadPlayerIndex);
ZEND_FUNCTION(SDL_GetGamepadButton);
ZEND_FUNCTION(SDL_GetGamepadAxis);
ZEND_FUNCTION(SDL_UpdateGamepads);
ZEND_FUNCTION(SDL_GetJoysticks);
ZEND_FUNCTION(SDL_OpenJoystick);
ZEND_FUNCTION(SDL_CloseJoystick);
ZEND_FUNCTION(SDL_GetJoystickName);
ZEND_FUNCTION(SDL_GetJoystickSerial);
ZEND_FUNCTION(SDL_GetJoystickPath);
ZEND_FUNCTION(SDL_GetJoystickPlayerIndex);
ZEND_FUNCTION(SDL_SetJoystickPlayerIndex);
ZEND_FUNCTION(SDL_GetNumJoystickAxes);
ZEND_FUNCTION(SDL_GetNumJoystickButtons);
ZEND_FUNCTION(SDL_GetNumJoystickHats);
ZEND_FUNCTION(SDL_GetJoystickAxis);
ZEND_FUNCTION(SDL_GetJoystickButton);
ZEND_FUNCTION(SDL_GetJoystickHat);
ZEND_FUNCTION(SDL_UpdateJoysticks);
ZEND_FUNCTION(SDL_AttachVirtualJoystick);
ZEND_FUNCTION(SDL_DetachVirtualJoystick);
ZEND_FUNCTION(SDL_SetJoystickVirtualAxis);
ZEND_FUNCTION(SDL_SetJoystickVirtualButton);
ZEND_FUNCTION(SDL_SetJoystickVirtualHat);
ZEND_METHOD(SDL_Gamepad, __construct);
ZEND_METHOD(SDL_Gamepad, pointer);
ZEND_METHOD(SDL_Gamepad, fromPointer);
ZEND_METHOD(SDL_Joystick, __construct);
ZEND_METHOD(SDL_Joystick, pointer);
ZEND_METHOD(SDL_Joystick, fromPointer);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(SDL_GetKeyboardFocus, arginfo_SDL_GetKeyboardFocus)
	ZEND_FE(SDL_StartTextInput, arginfo_SDL_StartTextInput)
	ZEND_FE(SDL_StopTextInput, arginfo_SDL_StopTextInput)
	ZEND_FE(SDL_TextInputActive, arginfo_SDL_TextInputActive)
	ZEND_FE(SDL_GetGamepads, arginfo_SDL_GetGamepads)
	ZEND_FE(SDL_IsGamepad, arginfo_SDL_IsGamepad)
	ZEND_FE(SDL_OpenGamepad, arginfo_SDL_OpenGamepad)
	ZEND_FE(SDL_CloseGamepad, arginfo_SDL_CloseGamepad)
	ZEND_FE(SDL_GetGamepadName, arginfo_SDL_GetGamepadName)
	ZEND_FE(SDL_GetGamepadID, arginfo_SDL_GetGamepadID)
	ZEND_FE(SDL_GetGamepadSerial, arginfo_SDL_GetGamepadSerial)
	ZEND_FE(SDL_GetGamepadPath, arginfo_SDL_GetGamepadPath)
	ZEND_FE(SDL_GetGamepadPlayerIndex, arginfo_SDL_GetGamepadPlayerIndex)
	ZEND_FE(SDL_SetGamepadPlayerIndex, arginfo_SDL_SetGamepadPlayerIndex)
	ZEND_FE(SDL_GetGamepadButton, arginfo_SDL_GetGamepadButton)
	ZEND_FE(SDL_GetGamepadAxis, arginfo_SDL_GetGamepadAxis)
	ZEND_FE(SDL_UpdateGamepads, arginfo_SDL_UpdateGamepads)
	ZEND_FE(SDL_GetJoysticks, arginfo_SDL_GetJoysticks)
	ZEND_FE(SDL_OpenJoystick, arginfo_SDL_OpenJoystick)
	ZEND_FE(SDL_CloseJoystick, arginfo_SDL_CloseJoystick)
	ZEND_FE(SDL_GetJoystickName, arginfo_SDL_GetJoystickName)
	ZEND_FE(SDL_GetJoystickSerial, arginfo_SDL_GetJoystickSerial)
	ZEND_FE(SDL_GetJoystickPath, arginfo_SDL_GetJoystickPath)
	ZEND_FE(SDL_GetJoystickPlayerIndex, arginfo_SDL_GetJoystickPlayerIndex)
	ZEND_FE(SDL_SetJoystickPlayerIndex, arginfo_SDL_SetJoystickPlayerIndex)
	ZEND_FE(SDL_GetNumJoystickAxes, arginfo_SDL_GetNumJoystickAxes)
	ZEND_FE(SDL_GetNumJoystickButtons, arginfo_SDL_GetNumJoystickButtons)
	ZEND_FE(SDL_GetNumJoystickHats, arginfo_SDL_GetNumJoystickHats)
	ZEND_FE(SDL_GetJoystickAxis, arginfo_SDL_GetJoystickAxis)
	ZEND_FE(SDL_GetJoystickButton, arginfo_SDL_GetJoystickButton)
	ZEND_FE(SDL_GetJoystickHat, arginfo_SDL_GetJoystickHat)
	ZEND_FE(SDL_UpdateJoysticks, arginfo_SDL_UpdateJoysticks)
	ZEND_FE(SDL_AttachVirtualJoystick, arginfo_SDL_AttachVirtualJoystick)
	ZEND_FE(SDL_DetachVirtualJoystick, arginfo_SDL_DetachVirtualJoystick)
	ZEND_FE(SDL_SetJoystickVirtualAxis, arginfo_SDL_SetJoystickVirtualAxis)
	ZEND_FE(SDL_SetJoystickVirtualButton, arginfo_SDL_SetJoystickVirtualButton)
	ZEND_FE(SDL_SetJoystickVirtualHat, arginfo_SDL_SetJoystickVirtualHat)
	ZEND_FE_END
};

static const zend_function_entry class_SDL_Gamepad_methods[] = {
	ZEND_ME(SDL_Gamepad, __construct, arginfo_class_SDL_Gamepad___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(SDL_Gamepad, pointer, arginfo_class_SDL_Gamepad_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(SDL_Gamepad, fromPointer, arginfo_class_SDL_Gamepad_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_SDL_Joystick_methods[] = {
	ZEND_ME(SDL_Joystick, __construct, arginfo_class_SDL_Joystick___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(SDL_Joystick, pointer, arginfo_class_SDL_Joystick_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(SDL_Joystick, fromPointer, arginfo_class_SDL_Joystick_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static void register_SDL_input_symbols(int module_number)
{
	REGISTER_STRING_CONSTANT("SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS", SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_INIT_JOYSTICK", SDL_INIT_JOYSTICK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_INIT_GAMEPAD", SDL_INIT_GAMEPAD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_SOUTH", SDL_GAMEPAD_BUTTON_SOUTH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_EAST", SDL_GAMEPAD_BUTTON_EAST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_WEST", SDL_GAMEPAD_BUTTON_WEST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_NORTH", SDL_GAMEPAD_BUTTON_NORTH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_BACK", SDL_GAMEPAD_BUTTON_BACK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_GUIDE", SDL_GAMEPAD_BUTTON_GUIDE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_START", SDL_GAMEPAD_BUTTON_START, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_LEFT_STICK", SDL_GAMEPAD_BUTTON_LEFT_STICK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_RIGHT_STICK", SDL_GAMEPAD_BUTTON_RIGHT_STICK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_LEFT_SHOULDER", SDL_GAMEPAD_BUTTON_LEFT_SHOULDER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER", SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_DPAD_UP", SDL_GAMEPAD_BUTTON_DPAD_UP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_DPAD_DOWN", SDL_GAMEPAD_BUTTON_DPAD_DOWN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_DPAD_LEFT", SDL_GAMEPAD_BUTTON_DPAD_LEFT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_BUTTON_DPAD_RIGHT", SDL_GAMEPAD_BUTTON_DPAD_RIGHT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_AXIS_LEFTX", SDL_GAMEPAD_AXIS_LEFTX, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_AXIS_LEFTY", SDL_GAMEPAD_AXIS_LEFTY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_AXIS_RIGHTX", SDL_GAMEPAD_AXIS_RIGHTX, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_AXIS_RIGHTY", SDL_GAMEPAD_AXIS_RIGHTY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_AXIS_LEFT_TRIGGER", SDL_GAMEPAD_AXIS_LEFT_TRIGGER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_GAMEPAD_AXIS_RIGHT_TRIGGER", SDL_GAMEPAD_AXIS_RIGHT_TRIGGER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_HAT_CENTERED", SDL_HAT_CENTERED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_HAT_UP", SDL_HAT_UP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_HAT_RIGHT", SDL_HAT_RIGHT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_HAT_DOWN", SDL_HAT_DOWN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_HAT_LEFT", SDL_HAT_LEFT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_JOYSTICK_TYPE_UNKNOWN", SDL_JOYSTICK_TYPE_UNKNOWN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_JOYSTICK_TYPE_GAMEPAD", SDL_JOYSTICK_TYPE_GAMEPAD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_JOYSTICK_AXIS_MIN", SDL_JOYSTICK_AXIS_MIN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_JOYSTICK_AXIS_MAX", SDL_JOYSTICK_AXIS_MAX, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_A", SDL_SCANCODE_A, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_B", SDL_SCANCODE_B, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_C", SDL_SCANCODE_C, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_D", SDL_SCANCODE_D, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_E", SDL_SCANCODE_E, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F", SDL_SCANCODE_F, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_G", SDL_SCANCODE_G, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_H", SDL_SCANCODE_H, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_I", SDL_SCANCODE_I, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_J", SDL_SCANCODE_J, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_K", SDL_SCANCODE_K, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_L", SDL_SCANCODE_L, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_M", SDL_SCANCODE_M, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_N", SDL_SCANCODE_N, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_O", SDL_SCANCODE_O, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_P", SDL_SCANCODE_P, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_Q", SDL_SCANCODE_Q, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_R", SDL_SCANCODE_R, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_S", SDL_SCANCODE_S, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_T", SDL_SCANCODE_T, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_U", SDL_SCANCODE_U, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_V", SDL_SCANCODE_V, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_W", SDL_SCANCODE_W, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_X", SDL_SCANCODE_X, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_Y", SDL_SCANCODE_Y, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_Z", SDL_SCANCODE_Z, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_1", SDL_SCANCODE_1, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_2", SDL_SCANCODE_2, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_3", SDL_SCANCODE_3, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_4", SDL_SCANCODE_4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_5", SDL_SCANCODE_5, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_6", SDL_SCANCODE_6, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_7", SDL_SCANCODE_7, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_8", SDL_SCANCODE_8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_9", SDL_SCANCODE_9, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_0", SDL_SCANCODE_0, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F1", SDL_SCANCODE_F1, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F2", SDL_SCANCODE_F2, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F3", SDL_SCANCODE_F3, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F4", SDL_SCANCODE_F4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F5", SDL_SCANCODE_F5, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F6", SDL_SCANCODE_F6, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F7", SDL_SCANCODE_F7, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F8", SDL_SCANCODE_F8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F9", SDL_SCANCODE_F9, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F10", SDL_SCANCODE_F10, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F11", SDL_SCANCODE_F11, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F12", SDL_SCANCODE_F12, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_UP", SDL_SCANCODE_UP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_DOWN", SDL_SCANCODE_DOWN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LEFT", SDL_SCANCODE_LEFT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RIGHT", SDL_SCANCODE_RIGHT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SPACE", SDL_SCANCODE_SPACE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RETURN", SDL_SCANCODE_RETURN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_ESCAPE", SDL_SCANCODE_ESCAPE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_TAB", SDL_SCANCODE_TAB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_BACKSPACE", SDL_SCANCODE_BACKSPACE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_DELETE", SDL_SCANCODE_DELETE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INSERT", SDL_SCANCODE_INSERT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_HOME", SDL_SCANCODE_HOME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_END", SDL_SCANCODE_END, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PAGEUP", SDL_SCANCODE_PAGEUP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PAGEDOWN", SDL_SCANCODE_PAGEDOWN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CAPSLOCK", SDL_SCANCODE_CAPSLOCK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LSHIFT", SDL_SCANCODE_LSHIFT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RSHIFT", SDL_SCANCODE_RSHIFT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LCTRL", SDL_SCANCODE_LCTRL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RCTRL", SDL_SCANCODE_RCTRL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LALT", SDL_SCANCODE_LALT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RALT", SDL_SCANCODE_RALT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LGUI", SDL_SCANCODE_LGUI, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RGUI", SDL_SCANCODE_RGUI, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MINUS", SDL_SCANCODE_MINUS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_EQUALS", SDL_SCANCODE_EQUALS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LEFTBRACKET", SDL_SCANCODE_LEFTBRACKET, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RIGHTBRACKET", SDL_SCANCODE_RIGHTBRACKET, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_BACKSLASH", SDL_SCANCODE_BACKSLASH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SEMICOLON", SDL_SCANCODE_SEMICOLON, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_APOSTROPHE", SDL_SCANCODE_APOSTROPHE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_GRAVE", SDL_SCANCODE_GRAVE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_COMMA", SDL_SCANCODE_COMMA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PERIOD", SDL_SCANCODE_PERIOD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SLASH", SDL_SCANCODE_SLASH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_0", SDL_SCANCODE_KP_0, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_1", SDL_SCANCODE_KP_1, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_2", SDL_SCANCODE_KP_2, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_3", SDL_SCANCODE_KP_3, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_4", SDL_SCANCODE_KP_4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_5", SDL_SCANCODE_KP_5, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_6", SDL_SCANCODE_KP_6, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_7", SDL_SCANCODE_KP_7, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_8", SDL_SCANCODE_KP_8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_9", SDL_SCANCODE_KP_9, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_DIVIDE", SDL_SCANCODE_KP_DIVIDE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MULTIPLY", SDL_SCANCODE_KP_MULTIPLY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MINUS", SDL_SCANCODE_KP_MINUS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_PLUS", SDL_SCANCODE_KP_PLUS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_ENTER", SDL_SCANCODE_KP_ENTER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_PERIOD", SDL_SCANCODE_KP_PERIOD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_EQUALS", SDL_SCANCODE_KP_EQUALS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PRINTSCREEN", SDL_SCANCODE_PRINTSCREEN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SCROLLLOCK", SDL_SCANCODE_SCROLLLOCK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PAUSE", SDL_SCANCODE_PAUSE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_NUMLOCKCLEAR", SDL_SCANCODE_NUMLOCKCLEAR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_APPLICATION", SDL_SCANCODE_APPLICATION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CLEAR", SDL_SCANCODE_CLEAR, CONST_PERSISTENT);
}

static zend_class_entry *register_class_SDL_Gamepad(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "SDL_Gamepad", class_SDL_Gamepad_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_SDL_Joystick(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "SDL_Joystick", class_SDL_Joystick_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_SDL_VirtualJoystickDesc(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "SDL_VirtualJoystickDesc", NULL);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	zval property_type_default_value;
	ZVAL_LONG(&property_type_default_value, 0);
	zend_string *property_type_name = zend_string_init("type", sizeof("type") - 1, 1);
	zend_declare_typed_property(class_entry, property_type_name, &property_type_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_type_name);

	zval property_vendor_id_default_value;
	ZVAL_LONG(&property_vendor_id_default_value, 0);
	zend_string *property_vendor_id_name = zend_string_init("vendor_id", sizeof("vendor_id") - 1, 1);
	zend_declare_typed_property(class_entry, property_vendor_id_name, &property_vendor_id_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_vendor_id_name);

	zval property_product_id_default_value;
	ZVAL_LONG(&property_product_id_default_value, 0);
	zend_string *property_product_id_name = zend_string_init("product_id", sizeof("product_id") - 1, 1);
	zend_declare_typed_property(class_entry, property_product_id_name, &property_product_id_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_product_id_name);

	zval property_naxes_default_value;
	ZVAL_LONG(&property_naxes_default_value, 0);
	zend_string *property_naxes_name = zend_string_init("naxes", sizeof("naxes") - 1, 1);
	zend_declare_typed_property(class_entry, property_naxes_name, &property_naxes_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_naxes_name);

	zval property_nbuttons_default_value;
	ZVAL_LONG(&property_nbuttons_default_value, 0);
	zend_string *property_nbuttons_name = zend_string_init("nbuttons", sizeof("nbuttons") - 1, 1);
	zend_declare_typed_property(class_entry, property_nbuttons_name, &property_nbuttons_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_nbuttons_name);

	zval property_nhats_default_value;
	ZVAL_LONG(&property_nhats_default_value, 0);
	zend_string *property_nhats_name = zend_string_init("nhats", sizeof("nhats") - 1, 1);
	zend_declare_typed_property(class_entry, property_nhats_name, &property_nhats_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_nhats_name);

	zval property_button_mask_default_value;
	ZVAL_LONG(&property_button_mask_default_value, 0);
	zend_string *property_button_mask_name = zend_string_init("button_mask", sizeof("button_mask") - 1, 1);
	zend_declare_typed_property(class_entry, property_button_mask_name, &property_button_mask_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_button_mask_name);

	zval property_axis_mask_default_value;
	ZVAL_LONG(&property_axis_mask_default_value, 0);
	zend_string *property_axis_mask_name = zend_string_init("axis_mask", sizeof("axis_mask") - 1, 1);
	zend_declare_typed_property(class_entry, property_axis_mask_name, &property_axis_mask_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_LONG));
	zend_string_release(property_axis_mask_name);

	zval property_name_default_value;
	ZVAL_EMPTY_STRING(&property_name_default_value);
	zend_string *property_name_name = zend_string_init("name", sizeof("name") - 1, 1);
	zend_declare_typed_property(class_entry, property_name_name, &property_name_default_value, ZEND_ACC_PUBLIC, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_STRING));
	zend_string_release(property_name_name);

	return class_entry;
}
